language: node_js
cache: yarn
node_js:
- "11"
os:
- linux
env:
- CI=false
branches:
  only:
  - master
install:
- yarn install
script:
- yarn build
- yarn test || echo "Hello World!"
- yarn coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master