language: node_js
cache: yarn
node_js:
- "11"
os:
- linux
branches:
  only:
  - master
install:
- yarn global add gulp-cli
- yarn install
script:
- gulp travis
- yarn coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
